name: Auto Update Dependency

on:
  schedule:
    - cron: "0 9 * * *" # every day at 9 AM UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  check-version:
    runs-on: ubuntu-latest
    outputs:
      latest: ${{ steps.check.outputs.latest }}
      current: ${{ steps.check.outputs.current }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up NodeJS v23
        uses: actions/setup-node@v4
        with:
          node-version: 23

      - name: Set current and latest versions
        id: check
        run: |
          LATEST=$(npm view material-symbols version)
          CURRENT=$(node -p "require('./package.json').devDependencies['material-symbols']")
          echo "latest=$LATEST" >> $GITHUB_OUTPUT
          echo "current=$CURRENT" >> $GITHUB_OUTPUT
          echo $CURRENT
          echo $LATEST

  update-and-release:
    needs: check-version
    if: ${{ needs.check-version.outputs.latest != needs.check-version.outputs.current }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.SECRET_PAT }}

      - name: Set up pnpm v10
        uses: pnpm/action-setup@v4

      - name: Set up NodeJS v23
        uses: actions/setup-node@v4
        with:
          cache: "pnpm"
          node-version: 23

      - name: Update material-symbols & run code update script
        run: |
          pnpm add material-symbols@${{ needs.check-version.outputs.latest }} --save-dev --save-exact
          pnpm version ${{ needs.check-version.outputs.latest }} --no-git-tag-version
          pnpm run import:all
          pnpm run build:all

      - name: Commit & tag release
        uses: EndBug/add-and-commit@v9
        with:
          message: "chore(update): update material-symbols to v${{ needs.check-version.outputs.latest }}"
          default_author: github_actions
          push: true
          tag: v${{ needs.check-version.outputs.latest }}
          tag_push: '--force'
          
      - uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ needs.check-version.outputs.latest }}
          name: "v${{ needs.check-version.outputs.latest }}"
          body: "Automated update to material-symbols v${{ needs.check-version.outputs.latest }}"
