name: Publish Package to npmjs

on:
  workflow_dispatch:
  push:
    # branches:
    #   - main
    tags:
      - v*.*.*

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v5

      - name: Set up pnpm v10
        uses: pnpm/action-setup@v4

      - name: Set up NodeJS v23
        uses: actions/setup-node@v4
        with:
          cache: "pnpm"
          node-version: 23
          registry-url: 'https://registry.npmjs.org'

      - run: pnpm install --frozen-lockfile

      - run: pnpm publish --provenance --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
