name: Publish Package to npmjs

on:
  workflow_dispatch:
  push:
    # branches:
    #   - main
    # tags:
    #   - v*.*.*

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v5

      - name: Set up pnpm v10
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Set up NodeJS v23
        uses: actions/setup-node@v4
        with:
          cache: "pnpm"
          node-version: 23

      - run: npm ci

      - run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
